---

- hosts: central
  become: true
  remote_user: vagrant

  tasks:
    - hostname: name=central

    - service: name=iptables enabled=no
    - service: name=iptables state=stopped

    - name: Add Zabbix repository
      yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present

    - name: Install Zabbix-Server
      yum: name=zabbix-server-mysql state=present

    - name: Install Zabbix-Web-Mysql
      yum: name=zabbix-web-mysql state=present

    - name: Install the Python MySQL module
      yum: name=MySQL-python

    - name: Install Mysql Server
      yum: name=mysql-server state=present

    - service: name=mysqld state=started
    - service: name=mysqld enabled=yes

    - name: Create zabbix database 
      mysql_db: name=zabbix state=present collation=utf8_general_ci
      register: mysql_db

    - mysql_user: name=zabbix password=zabbix priv=*.*:ALL state=present

    - name: Import schema sql
      mysql_db: state=import name=zabbix target=/usr/share/doc/zabbix-server-mysql-2.4.7/create/schema.sql
      when: mysql_db.changed

    - name: Import images sql
      mysql_db: state=import name=zabbix target=/usr/share/doc/zabbix-server-mysql-2.4.7/create/images.sql
      when: mysql_db.changed

    - name: Import data sql
      mysql_db: state=import name=zabbix target=/usr/share/doc/zabbix-server-mysql-2.4.7/create/data.sql
      when: mysql_db.changed

    - name: Change time zone
      command: sed -i 's/# php_value date.timezone Europe\/Riga/php_value date.timezone Europe\/Kiev/g' /etc/httpd/conf.d/zabbix.conf

    - name: Change Zabbix Server conf
      command: sed -i 's/# DBHost=localhost/DBHost=localhost/g' /etc/zabbix/zabbix_server.conf

    - name: Change Zabbix Server conf 2
      command: sed -i 's/# DBPassword=/DBPassword=zabbix/g' /etc/zabbix/zabbix_server.conf 

    - name: Install SNMPD
      yum: name=net-snmp-utils state=present
      yum: name=net-snmp state=present

    - service: name=snmpd state=restarted
    - service: name=snmpd enabled=yes

    - name: Install Apache HTTP
      yum: name=httpd state=latest
      yum: name=mod_ssl state=latest

    - name: Configure Zabbix frontend
      template: src=/vagrant/zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php owner=apache group=apache

    - name: Install Zabbix API
      pip: name=zabbix-api state=present

    - service: name=httpd state=restarted

    - service: name=httpd enabled=yes

    - service: name=zabbix-server enabled=yes

    - service: name=zabbix-server state=restarted

    - name: Import Rabbitmq Template
      command: python /vagrant/addtemplate.py rabbit.xml

    - name: Install Zabbix-Client
      yum: name=zabbix-agent state=present

    - service: name=zabbix-agent state=started

    - service: name=zabbix-agent enabled=yes

    - name: Install Zabbix Sender
      yum: name=zabbix-sender state=present

    - name: Add zabbix Item to config
      template: src=/vagrant/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf owner=zabbix group=zabbix

    - name: Add zabbix sudo on rabbitmqctl
      lineinfile: "dest=/etc/sudoers state=present line='%zabbix ALL=(ALL) NOPASSWD: /usr/sbin/rabbitmqctl'"
  
    - name: Restart zabbix agent
      service: name=zabbix-agent state=restarted

    - name: Install pika Library
      pip: name=pika state=present

    - name: Install Rabbitmq Server
      yum: name=rabbitmq-server state=present

    - service: name=rabbitmq-server state=started
    - service: name=rabbitmq-server enabled=yes

    - name: Enable Rabbitmq management plugin
      command: /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management

    - service: name=rabbitmq-server state=restarted

    - name: Add Host To zabbix Server
      local_action:
        module: zabbix_host
        server_url: http://10.10.10.3/zabbix
        login_user: admin
        login_password: zabbix
        host_name: central
        host_groups:
          - Linux Servers
        link_templates:
          - Template OS Linux
          - Rabbitmq Template
        status: enabled
        state: present
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 10.10.10.3
            dns: "central"
            port: 10050