---

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common

- hosts: central
  gather_facts: yes
  become: yes
  become_user: postgres
  roles:
    - central

- hosts: worker
  gather_facts: yes
  become: yes
  become_user: postgres
  roles:
    - worker

- hosts: central
  gather_facts: yes
  become: yes
  roles:
    - docker
