---

   - name: Install Docker
     shell: curl -fsSL https://get.docker.com/ | sh

   - name: Add docker group for vagrant user
     user: name=vagrant groups=docker append=yes

   - name: Start and enable Docker
     service: name=docker state=started enabled=yes

   - name: Build and run webapp containers
     shell: /vagrant/dockerfiles/webctl.sh deploy
