---

   - name: Install Docker
     shell: curl -fsSL https://get.docker.com/ | sh

   - name: Add docker group for centos user
     user: name=centos groups=docker append=yes

   - name: Reload Docker daemon
     command: systemctl daemon-reload

   - name: Restart docker service
     service: name=docker state=restarted

   - name: Enable Docker Service
     command: systemctl enable docker

   - name: Install pip
     yum: name=python-pip state=latest

   - name: Install docker-py
     pip: name=docker 
     
